name:                haskell-wav
version:             0.1.0.0
github:              "michaelheyman/haskell-wav"
license:             BSD3
author:              "Michael Heyman"
maintainer:          "michaelheyman@users.noreply.github.com"
copyright:           "2020 Michael Heyman"

ghc-options: -Wall -Werror

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-wav#readme>

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - attoparsec-binary
  - bytestring
  - text

library:
  source-dirs: src

executables:
  haskell-wav-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-wav

tests:
  haskell-wav-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - haskell-wav
    - hspec
    - hspec-attoparsec
